<a href="https://colab.research.google.com/github/BelemoualemChaimae/Web-Mining/blob/main/PageRank_with_two_ways.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from numpy import linalg as LA
import xml.etree.ElementTree as ET

In [ ]:
MatrixAdjangency=[[0,0,0,0,0,0,0,0,0,0,0],
                  [0,0,1,0,0,0,0,0,0,0,0],
                  [0,1,0,0,0,0,0,0,0,0,0],
                  [1,1,0,0,0,0,0,0,0,0,0],
                  [0,1,0,1,0,1,0,0,0,0,0],
                  [0,1,0,0,1,0,0,0,0,0,0],
                  [0,1,0,0,1,0,0,0,0,0,0],
                  [0,1,0,0,1,0,0,0,0,0,0],
                  [0,1,0,0,1,0,0,0,0,0,0],
                  [0,0,0,0,1,0,0,0,0,0,0],
                  [0,0,0,0,1,0,0,0,0,0,0]]

In [ ]:
landa=0.85
nlanda=1-landa

In [ ]:
epsillon=10**-6

In [ ]:
def Transation_probability(matrix,landa,nlanda):
    k=0
    links=0
    size=len(matrix)
    print(size)
    P= np.zeros((size,size)) 
    for i in range(size):
        for j in range(size):
            if matrix[i][j]==0:
                k=k+1
            else :
                links=links+1
        if k==size :
            for c in range(size):
                P[i][c]=1/size
        else :
            for l in range(size):
                 P[i][l]=(landa*(matrix[i][l]/links))+(nlanda*(1/size))
        links=0
        k=0
        
    return P

In [ ]:
print(Transation_probability(MatrixAdjangency,landa,nlanda))

11
[[0.09090909 0.09090909 0.09090909 0.09090909 0.09090909 0.09090909
  0.09090909 0.09090909 0.09090909 0.09090909 0.09090909]
 [0.01363636 0.01363636 0.86363636 0.01363636 0.01363636 0.01363636
  0.01363636 0.01363636 0.01363636 0.01363636 0.01363636]
 [0.01363636 0.86363636 0.01363636 0.01363636 0.01363636 0.01363636
  0.01363636 0.01363636 0.01363636 0.01363636 0.01363636]
 [0.43863636 0.43863636 0.01363636 0.01363636 0.01363636 0.01363636
  0.01363636 0.01363636 0.01363636 0.01363636 0.01363636]
 [0.01363636 0.2969697  0.01363636 0.2969697  0.01363636 0.2969697
  0.01363636 0.01363636 0.01363636 0.01363636 0.01363636]
 [0.01363636 0.43863636 0.01363636 0.01363636 0.43863636 0.01363636
  0.01363636 0.01363636 0.01363636 0.01363636 0.01363636]
 [0.01363636 0.43863636 0.01363636 0.01363636 0.43863636 0.01363636
  0.01363636 0.01363636 0.01363636 0.01363636 0.01363636]
 [0.01363636 0.43863636 0.01363636 0.01363636 0.43863636 0.01363636
  0.01363636 0.01363636 0.01363636 0.01363636 0.

In [ ]:
def pageRankVersion_(MatrixAdjangency,landa,epsilon):
  #Calculating the propability Matrix 
    size=len(MatrixAdjangency)
    P=Transation_probability(MatrixAdjangency,landa,1-landa)
    RP=np.ones((size))*1/size 
    l=0
    while True:
        RPP=RP.dot(P)
        dist = LA.norm(RPP-RP)
        l=l+1
        print("step :"+str(l)+"---------------------\n")
        print(RP)
        print("--------------------------------\n")
        
        if dist<=epsilon:
            return RP
        else :
            RP=RPP
            

In [ ]:
pageRankVersion_(MatrixAdjangency,landa,10**-6)

11
step :1---------------------

[0.09090909 0.09090909 0.09090909 0.09090909 0.09090909 0.09090909
 0.09090909 0.09090909 0.09090909 0.09090909 0.09090909]
--------------------------------

step :2---------------------

[0.05929752 0.31687328 0.09793388 0.04641873 0.32975207 0.04641873
 0.02066116 0.02066116 0.02066116 0.02066116 0.02066116]
--------------------------------

step :3---------------------

[0.03794641 0.2606909  0.28756073 0.1116482  0.09941335 0.1116482
 0.01821844 0.01821844 0.01821844 0.01821844 0.01821844]
--------------------------------

step :4---------------------

[0.06401907 0.40729181 0.23815585 0.0447357  0.11821894 0.0447357
 0.01656859 0.01656859 0.01656859 0.01656859 0.01656859]
--------------------------------

step :5---------------------

[0.03759596 0.31366142 0.36478133 0.05207866 0.08688751 0.05207866
 0.01858329 0.01858329 0.01858329 0.01858329 0.01858329]
--------------------------------

step :6---------------------

[0.03867494 0.41918432 0.2831

array([0.03278149, 0.38440062, 0.34291061, 0.03908709, 0.08088569,
       0.03908709, 0.01616948, 0.01616948, 0.01616948, 0.01616948,
       0.01616948])

In [ ]:
pages = ['A' , 'B' , 'C' , 'D' , 'E' , 'F' , 'G' , 'H' , 'I' , 'L' , 'M']
frame = pd.DataFrame(list(zip(pages , pageRankVersion_(MatrixAdjangency,landa,10**-6) )),columns=['pages','PageRankValue'])
frame

11
step :1---------------------

[0.09090909 0.09090909 0.09090909 0.09090909 0.09090909 0.09090909
 0.09090909 0.09090909 0.09090909 0.09090909 0.09090909]
--------------------------------

step :2---------------------

[0.05929752 0.31687328 0.09793388 0.04641873 0.32975207 0.04641873
 0.02066116 0.02066116 0.02066116 0.02066116 0.02066116]
--------------------------------

step :3---------------------

[0.03794641 0.2606909  0.28756073 0.1116482  0.09941335 0.1116482
 0.01821844 0.01821844 0.01821844 0.01821844 0.01821844]
--------------------------------

step :4---------------------

[0.06401907 0.40729181 0.23815585 0.0447357  0.11821894 0.0447357
 0.01656859 0.01656859 0.01656859 0.01656859 0.01656859]
--------------------------------

step :5---------------------

[0.03759596 0.31366142 0.36478133 0.05207866 0.08688751 0.05207866
 0.01858329 0.01858329 0.01858329 0.01858329 0.01858329]
--------------------------------

step :6---------------------

[0.03867494 0.41918432 0.2831

pages  PageRankValue
0      A       0.032781
1      B       0.384401
2      C       0.342911
3      D       0.039087
4      E       0.080886
5      F       0.039087
6      G       0.016169
7      H       0.016169
8      I       0.016169
9      L       0.016169
10     M       0.016169

In [ ]:
def pagerank_version_graph( G, dmp = 0.85, eps = 1.0e-5, max_iter = 100):
    """
        PageRank computes a ranking of the nodes in the graph G based on 
        the structure of the incoming links. It was originally designed as 
        an algorithm to rank web pages. 

        Parameters 
        ---------- 
        G           : xml path of graph
        M           : transation matrix; The adjacency matrix of the web graph
        dmp         : damping factor ; usually set to 0.85
        eps         : Pre-specified threshold (desired precision); used in Stopping condition
        max_iter    : Maximum number of iterations               ; used in Stopping condition

        Returns 
        ------- 
        pagerank : dictionary; Dictionary of nodes with PageRank as value
    """
    graph = ET.parse(G).getroot()
    nb_site = len(graph)

    # Transform graph from xml into dictionary 
    link_dict ={}
    for i,node in enumerate(graph):
        link_dict[node.get("link")] =[ i, [link.get('value') for link in node] ]
    print(link_dict)
    print('######################################')
    dangling_node=[]
    # dictionary 2 translation matrix
    M = [[0 for _ in range(nb_site)] for _ in range(nb_site)] # transition matrix
    for i,node in enumerate(link_dict):
         if len(link_dict[node][1]) > 0 : 
            for link in link_dict[node][1]:
                  M[link_dict[node][0]][link_dict[link][0]] = 1/len(link_dict[node][1])
         else :
                dangling_node.append(link_dict[node][0])
    
    print(dangling_node)
    M = np.array(M)
    print('M:')
    print(pd.DataFrame(M))
    R_old =np.asarray([1/nb_site for _ in range(nb_site)])
    cpp = 0
    P=Transation_probability(M,dmp,1-dmp) 
    print(P)
    l=0
    while True:
        RPP=R_old.dot(P)
        dist = LA.norm(RPP-R_old)
        cpp=cpp+1
        print("step :"+str(cpp)+"---------------------\n")

        print(R_old)
        print("--------------------------------\n")
        
        if dist<=eps or cpp > max_iter:
            print('Steps :',cpp)
            print('######################################')
            return {'id':list(range(nb_site)), 'link': list(link_dict), 'rank': R_old}
        else :
            R_old=RPP
            


In [ ]:
dict_ = pagerank_version_graph('graph.xml')
df = pd.DataFrame(dict_)
df.sort_values(by=['rank'], ascending=False, inplace=True)
df.reset_index(drop=True,inplace=True)
df

{'page1': [0, ['page3', 'page4']], 'page2': [1, ['page3', 'page4']], 'page3': [2, []], 'page4': [3, ['page3', 'page1']]}
######################################
[2]
M:
     0    1    2    3
0  0.0  0.0  0.5  0.5
1  0.0  0.0  0.5  0.5
2  0.0  0.0  0.0  0.0
3  0.5  0.0  0.5  0.0
4
[[0.0375 0.0375 0.25   0.25  ]
 [0.0375 0.0375 0.25   0.25  ]
 [0.25   0.25   0.25   0.25  ]
 [0.25   0.0375 0.25   0.0375]]
step :1---------------------

[0.25 0.25 0.25 0.25]
--------------------------------

step :2---------------------

[0.14375  0.090625 0.25     0.196875]
--------------------------------

step :3---------------------

[0.12050781 0.07867188 0.1703125  0.12847656]
--------------------------------

step :4---------------------

[0.0821665  0.05486523 0.12449219 0.09719092]
--------------------------------

step :5---------------------

[0.06055947 0.0399064  0.08967871 0.06902564]
--------------------------------

step :6---------------------

[0.04344356 0.02877561 0.06479255 0.05012461]
--

id   link      rank
0   2  page3  0.000019
1   3  page4  0.000015
2   0  page1  0.000013
3   1  page2  0.000008